In [1]:
import numpy as np


In [3]:
n1=np.array([10,20,30,40,50])


In [4]:
n1

array([10, 20, 30, 40, 50])

In [24]:
nn1=np.array([[4,5,6],[7,8,9]])
nn1

array([[4, 5, 6],
       [7, 8, 9]])

In [22]:
n2=np.array([[1,2,3,4],[5,6,7,8]])

In [10]:
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
#initializing numpy with zero 


In [12]:
n3=np.zeros((1,2))

In [13]:
n3

array([[0., 0.]])

In [14]:
n4=np.zeros((5,5))

In [15]:
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
#initializing array with same number #using npwithfull

In [17]:
n5=np.full((2,2),10)
n5

array([[10, 10],
       [10, 10]])

In [18]:
#using np with full


In [19]:
n6=np.full((9,8),100)
n6


array([[100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100]])

In [25]:
#initialize numpy with a range

In [26]:
n7=np.arange(1,100)
n7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
n8=np.arange(1,5,2)
n8

array([1, 3])

In [37]:
n9=np.arange(0,10,2)
n9

array([0, 2, 4, 6, 8])

In [38]:
#Initializing np with random

In [42]:
nrandom=np.random.randint(1,30000,500)
nrandom

array([16919, 12115, 10219, 17031,  1446,  2390, 27603, 26580, 18236,
        5510,  9346, 16168,  9679, 29710, 18905,  2429, 16776, 21241,
        7099,  9763, 24390, 10427, 23727, 10023,  7153, 15820, 18901,
       18040,  7109, 22767, 12449, 26890,  1558, 18752,  2324, 13825,
        7795,  5923,  9113, 25578,  3156, 28692,  2280, 15397, 23558,
        2012,  1729, 10099, 29906, 29526,  9482,  6647, 20963, 29870,
       21035,  2951,  9995, 19732, 12466,  7829,  3719, 13046,  4702,
       25014, 13355, 25221, 19477, 21467,  3649,  8037, 29300,  5714,
        2746, 25260,  8474, 25855, 16292,  6523,   828,  8887, 27810,
        7414, 23415, 14211, 18787, 13936, 22340, 15769,  7552,  7904,
       13845, 16946, 23432, 27111, 18053, 19245, 20722, 11187, 23198,
        6669,  6403, 13682, 29224,  6989, 28412, 27429, 26200,  3524,
       27646,  6750,  4441, 13053, 15013, 14551, 28358, 28052,  7275,
       18705, 23831,  6526, 19687, 12007,  7128, 20300, 17996, 19552,
       16240, 11699,