In [2]:
import numpy as np

In [3]:
n1=np.array([10,40])
n2=np.array([20,30])

In [4]:
np.sum([n1,n2])

100

In [13]:
np.sum([n1,n2],axis=0)

array([30, 70])

In [14]:
np.sum([n1,n2],axis=1)

array([50, 50])

In [16]:
sub=n1-n2
sub

array([-10,  10])

In [18]:
mul=n1*n2
mul

array([ 200, 1200])

In [19]:
div=n1/n2
div

array([0.5       , 1.33333333])

In [20]:
#mean,median, and standard devision


In [ ]:
data=np.array([25,29,35,18,19,26,])