In [1]:
import numpy as np



In [ ]:
#for shape of array

In [9]:
n1=np.array([[1,2,3,4],[2,3,4,5]])
n1.shape

(2, 4)

In [16]:
n1.shape=(4,2)
n1

array([[1, 2],
       [3, 4],
       [2, 3],
       [4, 5]])

In [ ]:
# for vstack(),nkstack(),columnstack()

In [17]:
n2=np.array([10,20,30])
n3=np.array([40,50,60])


In [19]:
np.vstack((n2,n3))

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
np.hstack((n2,n3))

array([10, 20, 30, 40, 50, 60])

In [24]:
np.column_stack((n2,n3))


array([[10, 40],
       [20, 50],
       [30, 60]])

In [26]:
n4=np.array([40,50,60,70])
n5=np.array([70,80,90,100])
np.intersect1d(n4,n5)


array([70])

In [27]:
np.setdiff1d(n4,n5)

array([40, 50, 60])

In [28]:
np.setdiff1d(n5,n4)

array([ 80,  90, 100])